CREATE DATABASE DB_ENCUESTA
GO

USE DB_ENCUESTA
GO

/************* TABLE USER ****************/
/****************************************/
IF(NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_USER'))
BEGIN
	CREATE TABLE TBL_USER(
		USER_ID  UNIQUEIDENTIFIER DEFAULT (NEWID()),
		USERNAME VARCHAR(100) NOT NULL UNIQUE,
		PASSWORD VARBINARY(MAX) NOT NULL,
		SALT VARBINARY(MAX) NOT NULL,
		PRIMARY KEY(USER_ID)
	)
END;



/************ TABLE PROFILE ************/
/***********************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_PROFILE'))
BEGIN

  CREATE TABLE TBL_PROFILE(
    PROFILE_ID			UNIQUEIDENTIFIER DEFAULT(NEWID()),
	IDENTIFICATION		VARCHAR(15) NOT NULL UNIQUE,
	NAME				VARCHAR(100) NOT NULL,
	EMAIL				VARCHAR(100) NOT NULL UNIQUE,
	IMG_URL				VARCHAR(2083),
	CREATE_DATE			DATETIME NOT NULL,
	ACTIVE				BIT NOT NULL,
	USER_ID				UNIQUEIDENTIFIER DEFAULT(NEWID())
    PRIMARY KEY(PROFILE_ID)
  )

END;



/************ TABLE USER CLAIMS ************/
/************************************/
IF(NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TBL_USER_CLAIM'))
BEGIN

	CREATE TABLE TBL_USER_CLAIM(
		ID			INT IDENTITY(1,1),
		USER_ID		UNIQUEIDENTIFIER NOT NULL,
		CLAIM_VALUE VARCHAR(30) NOT NULL,
		CLAIM_TYPE	VARCHAR(30) NOT NULL,
		PRIMARY KEY(ID)
	)
END
GO



/************ TABLE TOPIC ************/
/************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_TOPIC'))
BEGIN

  CREATE TABLE TBL_TOPIC(
    TOPIC_ID			UNIQUEIDENTIFIER NOT NULL,
	TITLE				VARCHAR(100) NOT NULL,
	TOPIC_DESCRIPTION	VARCHAR(500) NOT NULL,
	IMG_URL				VARCHAR(2083),
	CREATE_DATE			DATE NOT NULL,
	USER_ID				UNIQUEIDENTIFIER DEFAULT(NEWID())
    PRIMARY KEY(TOPIC_ID)
  )

END;



/************ TABLE QUESTION ************/
/***************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_QUESTION'))
BEGIN

  CREATE TABLE TBL_QUESTION(
    QUESTION_ID			INT NOT NULL IDENTITY(1,1),
	QUESTION_DESCRIPTION	VARCHAR(500) NOT NULL,
	TOPIC_ID				INT NOT NULL,
    PRIMARY KEY(QUESTION_ID)
  )

END;



/************ TABLE ANSWER ************/
/*************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_ANSWER'))
BEGIN

  CREATE TABLE TBL_ANSWER(
    ANSWER_ID			INT NOT NULL IDENTITY(1,1),
	ANSWER_DESCRIPTION	VARCHAR(500) NOT NULL,
	QUESTION_ID				INT NOT NULL,
    PRIMARY KEY(ANSWER_ID)
  )

END;



/************ TABLE EXCEPTION ************/
/****************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_EXCEPTION'))
BEGIN

  CREATE TABLE TBL_EXCEPTION(
    EXCEPTION_ID		INT NOT NULL IDENTITY(1,1),
	CODE				INT NOT NULL UNIQUE,
	MESSAGE				VARCHAR(500) NOT NULL,
    PRIMARY KEY(EXCEPTION_ID)
  )

END;



/************ TABLE UNCONTROLLED EXCEPTION ************/
/*****************************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_UNCONTROLLED_EXCEPTION'))
BEGIN

  CREATE TABLE TBL_UNCONTROLLED_EXCEPTION(
    UNCONTROLLED_EXCEPTION_ID	INT NOT NULL IDENTITY(1,1),
	MESSAGE						VARCHAR(500) NOT NULL,
	EXC_HOUR					TIME NOT NULL,
	EXC_DAY						DATE NOT NULL,
	STACK_TRACE					VARCHAR(MAX),
    PRIMARY KEY(UNCONTROLLED_EXCEPTION_ID)
  )
END;



/************ TABLE ROLE ************/
/************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_ROLE'))
BEGIN

  CREATE TABLE TBL_ROLE(
    ROLE_ID			INT NOT NULL IDENTITY(1,1),
	ROLE_NAME		VARCHAR(20) NOT NULL
    PRIMARY KEY(ROLE_ID)
  )

END;



/************ TABLE CATEGORY ************/
/************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_CATEGORY'))
BEGIN

  CREATE TABLE TBL_CATEGORY(
    CATEGORY_ID			INT NOT NULL IDENTITY(1,1),
	CATEGORY_NAME		VARCHAR(20) NOT NULL
    PRIMARY KEY(CATEGORY_ID)
  )

END;



/************ TABLE CATEGORY BY TOPIC************/
/************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_CATEGORY_BY_TOPIC'))
BEGIN

  CREATE TABLE TBL_CATEGORY_BY_TOPIC(
    ID				INT NOT NULL IDENTITY(1,1),
	CATEGORY_ID		INT NOT NULL,
	TOPIC_ID		INT NOT NULL,
    PRIMARY KEY(ID)
  )

END;



/************ TABLE ROLE BY USER ************/
/************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_ROLE_BY_USER'))
BEGIN

  CREATE TABLE TBL_ROLE_BY_USER(
    ID			INT NOT NULL IDENTITY(1,1),
	ROLE_ID		INT NOT NULL,
	USER_ID		UNIQUEIDENTIFIER DEFAULT(NEWID())
    PRIMARY KEY(ID)
  )

END;



/********************************************************************/
/**************************FOREIGN KEYS*****************************/
/******************************************************************/
ALTER TABLE TBL_PROFILE ADD FOREIGN KEY (USER_ID)
REFERENCES TBL_USER(USER_ID) ON UPDATE CASCADE

ALTER TABLE TBL_TOPIC ADD FOREIGN KEY (USER_ID)
REFERENCES TBL_USER(USER_ID) ON UPDATE CASCADE

ALTER TABLE TBL_QUESTION ADD FOREIGN KEY (TOPIC_ID)
REFERENCES TBL_TOPIC(TOPIC_ID) ON UPDATE CASCADE

ALTER TABLE TBL_ANSWER ADD FOREIGN KEY (QUESTION_ID)
REFERENCES TBL_QUESTION(QUESTION_ID) ON UPDATE CASCADE

ALTER TABLE TBL_CATEGORY_BY_TOPIC ADD FOREIGN KEY (CATEGORY_ID)
REFERENCES TBL_CATEGORY(CATEGORY_ID) ON UPDATE CASCADE

ALTER TABLE TBL_CATEGORY_BY_TOPIC ADD FOREIGN KEY (TOPIC_ID)
REFERENCES TBL_TOPIC(TOPIC_ID) ON UPDATE CASCADE

ALTER TABLE TBL_ROLE_BY_USER ADD FOREIGN KEY (ROLE_ID)
REFERENCES TBL_ROLE(ROLE_ID)ON UPDATE CASCADE

ALTER TABLE TBL_ROLE_BY_USER ADD FOREIGN KEY (USER_ID)
REFERENCES TBL_USER(USER_ID)ON UPDATE CASCADE ON DELETE CASCADE



/****************************************************************************/
/****************************REQUIRED RECORDS*******************************/
/**************************************************************************/
INSERT INTO TBL_ROLE VALUES('ADMIN');
INSERT INTO TBL_ROLE VALUES('STANDARD_USER');
INSERT INTO TBL_ROLE VALUES('MANAGER')

INSERT INTO TBL_EXCEPTION VALUES(1,'Upps algo fallo!');
INSERT INTO TBL_EXCEPTION VALUES(2,'Por favor completar los campos requeridos');
INSERT INTO TBL_EXCEPTION VALUES(3,'Por favor ingrese un correo o numero de cedula diferente, ya se encuentran registrado');
INSERT INTO TBL_EXCEPTION VALUES(4,'El usuario no existe');
INSERT INTO TBL_EXCEPTION VALUES(5,'La pregunta no existe');
INSERT INTO TBL_EXCEPTION VALUES(6,'El tema no existe');

SELECT * FROM TBL_USER
SELECT * FROM TBL_PROFILE
SELECT * FROM TBL_USER_CLAIM
SELECT * FROM TBL_TOPIC
SELECT *  FROM TBL_UNCONTROLLED_EXCEPTION
INSERT INTO TBL_USER_CLAIM VALUES('FBB2FAB0-87F0-4683-8C65-E148EC06616B','ADMIN','Roles')


