CREATE DATABASE DB_ENCUESTA
GO

USE DB_ENCUESTA
GO



/************ TABLE USER ************/
/***********************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_PROFILE'))
BEGIN

  CREATE TABLE TBL_PROFILE(
    PROFILE_ID			INT NOT NULL IDENTITY(1,1),
	IDENTIFICATION		VARCHAR(15) NOT NULL UNIQUE,
	NAME				VARCHAR(100) NOT NULL,
	EMAIL				VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD			VARBINARY(MAX),
	SALT				VARBINARY(MAX),
	IMG_URL				VARCHAR(2083),
	CREATE_DATE			DATETIME NOT NULL,
	ACTIVE				BIT NOT NULL,			
    PRIMARY KEY(PROFILE_ID)
  )

END;



/************ TABLE TOPIC ************/
/************************************/
IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE 
TABLE_NAME = 'TBL_TOPIC'))
BEGIN

  CREATE TABLE TBL_TOPIC(
    TOPIC_ID			INT NOT NULL IDENTITY(1,1),
	TITLE				VARCHAR(100) NOT NULL,
	TOPIC_DESCRIPTION	VARCHAR(500) NOT NULL,
	IMG_URL				VARCHAR(2083),
	CREATE_DATE			DATE NOT NULL,
	USER_ID				INT NOT NULL,
    PRIMARY KEY(TOPIC_ID)
  )

END;



/********************************************************************/
/**************************FOREIGN KEYS*****************************/
/******************************************************************/

ALTER TABLE TBL_TOPIC ADD FOREIGN KEY (USER_ID)
REFERENCES TBL_PROFILE(PROFILE_ID) ON UPDATE CASCADE